### ISSUE TITLE
Using localFuntionsTestnet error ( event="noNetwork", code=NETWORK_ERROR )

### ISSUE THREAD

**Issue by claudiovb** [smartcontractkit/functions-toolkit#45]
I'm using the [Functions Hardhat Starter Kit](https://github.com/smartcontractkit/functions-hardhat-starter-kit) as recommended on the readMe of this repo and each time I try to run the command to start the local testnet I have this issue when helper tries to deploy the oracle functions:
`/Users/claudiovilasboas/Desktop/Pollum/TSNHack/lyra-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269
        const error: any = new Error(message);
                           ^
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)`
Additionally, I tried to manually initiate the node with the hardhat node and then I got an issue of no funds to deploy the contracts given the fact that the startLocalFunctionsTestnet still tries to spin up a ganache server and use those addresses to deploy the contracts on the localTestnet.

**Comment by claudiovb** [comment]
Update here, I've made a dummy patch on my fork of functions, and it's working fine with hardhat on my local Env:
https://github.com/claudiovb/functions-toolkit

**Comment by zeuslawyer** [comment]
Thanks for raising @claudiovb  - looking into it.

**Comment by zeuslawyer** [comment]
Appears to have something to do with Node V18 and above, and ethersjs
https://github.com/ethers-io/ethers.js/issues/4331

**Comment by KuphJr** [comment]
Thanks for reporting! I am looking into this. We may be making some modifications to the local testnet node which might resolve this within the next month or so. I'll update this thread then.

**Comment by zeuslawyer** [comment]
Closing this issue. Please reopen if it persists.
