### ISSUE TITLE
Remote code location support confirmation

### ISSUE THREAD

**Issue by outerlook** [smartcontractkit/functions-toolkit#72]
Hey! I Noticed 2 things:
- local testnet setup errors with `syntax error, RAM exceeded, or other error` for [very simple code](https://gist.github.com/outerlook/098cd44e8cee3114321720a9221d5dd9/raw) that works when using inline location
- Sepolia also doesn't work with these sources. Using `Remote` location I get success on the request TX but at chainlink UI I get `Invalid code location` on code execution panel

I also have many tests locally that works perfectly with the testnet, but it's too expensive to have this source on chain

I can't find information about this anywhere (as it doesn't show in tutorials) and am also trying to [use the Discord channel](https://discordapp.com/channels/592041321326182401/1080516970765623437/1316057531822641243) to reach for assistance. I understand that the team can be spread thin to check everywhere, so where do you recommend to reach for assistance in the future?

**Comment by zeuslawyer** [comment]
Hi @outerlook 
Code location must be `0` for inline.   This can be hard-coded into the solidity contract OR can be passed in as a CBOR encoded Functions Request. 
Please see: https://github.com/smartcontractkit/functions-toolkit?tab=readme-ov-file#building-functions-request-cbor-bytes

**Comment by outerlook** [comment]
Alright! Thank you @zeuslawyer
